/**
 * i18n/hi-pilot.js — Hindi pilot dictionary (Phase 37 / cowork, LTR).
 *
 * The same curated **core-pages** surface as the French and Urdu pilots (shared shell + homepage
 * price surface), translated into Hindi (Devanagari). Hindi is left-to-right, so it reuses the
 * default LTR infrastructure — `getLocaleDir('hi') === 'ltr'` / `isRtlLocale('hi') === false`.
 *
 * Like the French/Urdu pilots it is kept OUT of the parity-guarded `src/config/translations.js`
 * (EN/AR are held to exact key parity; Hindi is a partial pilot). Every key here MUST exist in
 * `TRANSLATIONS.en` (guarded by tests); uncovered keys fall back to English via the shared
 * `translate()` helper. The reference-estimate framing (bullion-equivalent, "not financial advice")
 * is preserved verbatim in meaning, and the immutable constants (USD/AED labels, the AED fixed peg,
 * data-source names) are carried through unchanged.
 *
 * Scope note: this is inert scaffolding, exactly like fr/ur — no runtime file consumes the locale
 * registry or these helpers yet; live hreflang/switcher are generated by separate SEO scripts. The
 * pilot ships as a test-covered dictionary so a later phase can wire it in behind linguist review.
 */

/** @type {Record<string, string>} — Hindi strings, keyed by the existing EN translation key. */
export const HI_PILOT = {
  // ── Header / language ──────────────────────────────────────────────────────
  'header.title': 'सोने की कीमतें लाइव',
  'header.subtitle': 'कैरेट और मुद्रा के अनुसार स्पॉट-आधारित बुलियन अनुमान',
  'lang.toggle': 'English',

  // ── Primary navigation ─────────────────────────────────────────────────────
  'nav.home': 'होम',
  'nav.tracker': 'लाइव ट्रैकर',
  'nav.calculator': 'कैलकुलेटर',
  'nav.learn': 'सीखने का केंद्र',
  'nav.shops': 'दुकानें और बाज़ार',
  'nav.methodology': 'कार्यप्रणाली',
  'nav.terms': 'सेवा की शर्तें',
  'nav.privacy': 'गोपनीयता नीति',
  'nav.invest': 'निवेश',
  'nav.insights': 'बाज़ार विश्लेषण',
  'nav.countries': 'देश',
  'nav.compare': 'देशों की तुलना',
  'nav.heatmap': 'विश्व मानचित्र',
  'nav.glossary': 'शब्दावली',
  'nav.market': 'सोने की कीमत कैसे तय होती है',
  'nav.portfolio': 'पोर्टफोलियो',
  'nav.dubai': 'दुबई और यूएई में सोने की कीमत',
  'nav.country': 'देश',
  'breadcrumbs.ariaLabel': 'ब्रेडक्रम्ब',

  // ── Footer ─────────────────────────────────────────────────────────────────
  'footer.goldSource': 'सोने का डेटा: Gold-API.com (gold-api.com)',
  'footer.fxSource': 'मुद्रा विनिमय डेटा: ExchangeRate-API (open.er-api.com)',
  'footer.disclaimer':
    'केवल बुलियन-समतुल्य अनुमानित मूल्य। खुदरा और आभूषण की कीमतें काफ़ी भिन्न हो सकती हैं। यह वित्तीय सलाह नहीं है।',

  // ── Gold / FX / AED freshness + badges ─────────────────────────────────────
  'gold.freshness.label': 'सोना अपडेट हुआ:',
  'gold.countdown.label': 'अगला अपडेट:',
  'gold.badge': 'लाइव',
  'fx.freshness.label': 'विनिमय दरें अपडेट हुईं:',
  'fx.next.label': 'अगला मुद्रा अपडेट:',
  'fx.badge': 'दैनिक',
  'aed.badge': 'निश्चित पेग',
  'aed.note': 'यूएई सेंट्रल बैंक की अमेरिकी डॉलर से आधिकारिक पेग',

  // ── Homepage spotlight ─────────────────────────────────────────────────────
  'spotlight.title': 'यूएई में सोने की कीमतें',
  'spotlight.note': 'बुलियन-समतुल्य अनुमानित मूल्य',
  'spotlight.perOzUsd': 'प्रति औंस (USD)',
  'spotlight.perOzAed': 'प्रति औंस (AED)',
  'spotlight.perGramUsd': 'प्रति ग्राम (USD)',
  'spotlight.perGramAed': 'प्रति ग्राम (AED)',
  'spotlight.karat.label': 'कैरेट:',

  // ── Price movement ─────────────────────────────────────────────────────────
  'change.title': 'कीमत में बदलाव',
  'change.vsPrev': 'पिछले रिकॉर्ड की तुलना में',
  'change.vsOpen': 'दुबई की शुरुआती कीमत की तुलना में',
  'change.note': '24 कैरेट प्रति औंस · USD · स्पॉट-आधारित अनुमान',

  // ── Price-by-karat table ───────────────────────────────────────────────────
  'karat.title': 'कैरेट के अनुसार कीमत',
  'karat.col.karat': 'कैरेट',
  'karat.col.usd': 'USD',
  'karat.col.aed': 'AED (निश्चित पेग)',
  'karat.disclaimer':
    'बुलियन-समतुल्य अनुमानित मूल्य। खुदरा और आभूषण की कीमतें भिन्न हो सकती हैं। यह वित्तीय सलाह नहीं है।',

  // ── Units ──────────────────────────────────────────────────────────────────
  'unit.gram': 'प्रति ग्राम',
  'unit.oz': 'प्रति औंस',

  // ── Country / price cards ──────────────────────────────────────────────────
  'card.perGram': 'प्रति ग्राम',
  'card.perOz': 'प्रति औंस',
  'card.copy': 'कॉपी',
  'card.copied': 'कॉपी हो गया!',
  'card.stale': 'पुराना',
  'card.noData': 'कोई डेटा नहीं',
  'card.addFavorite': 'पसंदीदा में जोड़ें',
  'card.removeFavorite': 'पसंदीदा से हटाएँ',

  // ── Status / freshness messages ────────────────────────────────────────────
  'status.loading': 'कीमतें लोड हो रही हैं...',
  'status.offline': 'आप ऑफ़लाइन हैं। सहेजा गया डेटा दिखाया जा रहा है।',
  'status.goldStale': 'सोने का डेटा पुराना हो सकता है। सहेजी गई कीमत का उपयोग किया जा रहा है।',
  'status.fxStale': 'विनिमय दरें पुरानी हो सकती हैं। सहेजी गई दरों का उपयोग किया जा रहा है।',
  'status.goldError':
    'सोने की कीमत ताज़ा नहीं की जा सकी। उपलब्ध होने पर अंतिम सहेजा गया मान दिखाया जा रहा है।',
  'status.fxError':
    'विनिमय दरें ताज़ा नहीं की जा सकीं। उपलब्ध होने पर अंतिम सहेजी गई दरें दिखाई जा रही हैं।',
  'status.noData': 'कीमतें अभी उपलब्ध नहीं हैं। अपना कनेक्शन जाँचें और पुनः प्रयास दबाएँ।',
  'status.retry': 'पुनः प्रयास करें',
  'status.cacheHealth': 'डेटा ताज़गी:',
};

/** Keys covered by the Hindi pilot. Everything else falls back to English. */
export const HI_PILOT_KEYS = Object.keys(HI_PILOT);

/**
 * Return a translations map with the Hindi pilot grafted on as the `hi` locale, so
 * `translate(withHindiPilot(TRANSLATIONS), 'hi', key)` yields Hindi for covered keys and English for
 * the rest. The input map is not mutated.
 *
 * @param {Record<string, Record<string, string>>} translations  e.g. `TRANSLATIONS`.
 * @returns {Record<string, Record<string, string>>}
 */
export function withHindiPilot(translations) {
  return { ...(translations || {}), hi: HI_PILOT };
}
