// components/nav-data.js — bilingual nav menu content data
// Edit this file to add/remove nav items, dropdowns, and labels.

export const NAV_DATA = {
  en: {
    home:  { href: '../index.html',  label: 'Home'  },
    shops: { href: '../shops.html',  label: 'Shops' },
    invest: { href: '../invest.html', label: 'Invest' },
    groups: [
      {
        key: 'markets',
        label: 'Markets',
        description: 'Live tracker, GCC compare & historical data',
        items: [
          { href: '../tracker.html',                   label: 'Live Tracker'   },
          { href: '../countries/uae.html',             label: 'UAE Gold Today' },
          { href: '../tracker.html#mode=compare',        label: 'GCC Compare'    },
          { href: '../countries/index.html',            label: 'Country Pages'  },
          { href: '../tracker.html#mode=archive',        label: 'History & Data' },
        ],
      },
      {
        key: 'tools',
        label: 'Tools',
        description: 'Calculator, alerts, exports & price history',
        items: [
          { href: '../calculator.html',                label: 'Calculator'       },
          { href: '../tools/weight-converter.html',    label: 'Weight Converter' },
          { href: '../tools/zakat-calculator.html',    label: 'Zakat Calculator' },
          { href: '../tools/investment-return.html',   label: 'Investment Return'},
          { href: '../tracker.html#mode=live&panel=alerts',         label: 'Alerts'       },
          { href: '../tracker.html#mode=exports',        label: 'Downloads'    },
          { href: '../gold-price-history/',              label: 'Price History' },
          { href: '../order-gold/',                      label: 'Order Gold'   },
          { href: '../search/',                          label: 'Search'       },
          { href: '../social/x-post-generator.html',    label: 'X Post Generator' },
        ],
      },
      {
        key: 'cities',
        label: 'Cities',
        description: 'Gold prices by city across the Arab world',
        items: [
          { href: '../countries/uae/cities/dubai.html',           label: 'Dubai, UAE'           },
          { href: '../countries/uae/cities/abu-dhabi.html',       label: 'Abu Dhabi, UAE'       },
          { href: '../countries/saudi-arabia/cities/riyadh.html', label: 'Riyadh, Saudi Arabia' },
          { href: '../countries/egypt/cities/cairo.html',         label: 'Cairo, Egypt'         },
          { href: '../countries/qatar/cities/doha.html',          label: 'Doha, Qatar'          },
        ],
      },
      {
        key: 'goldmarkets',
        label: 'Famous Markets',
        description: 'Famous gold souks and bazaars',
        items: [
          { href: '../countries/uae/markets/dubai-gold-souk.html',         label: 'Dubai Gold Souk'         },
          { href: '../countries/egypt/markets/khan-el-khalili-cairo.html', label: 'Khan el-Khalili, Cairo' },
        ],
      },
      {
        key: 'learn',
        label: 'Learn',
        description: 'Guides, methodology & FAQs',
        items: [
          { href: '../guides/buying-guide.html',          label: 'How to Buy Gold'     },
          { href: '../guides/24k-vs-22k.html',            label: '24K vs 22K Gold'     },
          { href: '../guides/gold-karat-comparison.html',  label: 'Karat Comparison'    },
          { href: '../guides/aed-peg-explained.html',      label: 'AED Peg Explained'   },
          { href: '../guides/gcc-market-hours.html',       label: 'GCC Market Hours'    },
          { href: '../guides/invest-in-gold-gcc.html',     label: 'Invest in Gold (GCC)'},
          { href: '../guides/zakat-gold-guide.html',       label: 'Zakat on Gold'       },
          { href: '../learn.html',                         label: 'Gold Guide'          },
          { href: '../methodology.html',                   label: 'Methodology'         },
          { href: '../learn.html#faq',                     label: 'FAQ'                 },
        ],
      },
      {
        key: 'insights',
        label: 'Insights',
        description: 'Market analysis & weekly briefs',
        items: [
          { href: '../insights.html',                label: 'Gold Insights'        },
          { href: '../insights.html#why-gold-moved', label: 'Why Gold Moved Today' },
          { href: '../insights.html#weekly-brief',   label: 'Weekly Brief'         },
        ],
      },
    ],
    langToggle: 'العربية',
    openMenu:   'Open menu',
    closeMenu:  'Close menu',
    mainNav:    'Main navigation',
  },

  ar: {
    home:  { href: '../index.html',  label: 'الرئيسية'    },
    shops: { href: '../shops.html',  label: 'المحلات'     },
    invest: { href: '../invest.html', label: 'الاستثمار' },

    groups: [
      {
        key: 'markets',
        label: 'الأسواق',
        description: 'متتبع مباشر، مقارنة الخليج والبيانات التاريخية',
        items: [
          { href: '../tracker.html',                   label: 'تتبع مباشر'          },
          { href: '../countries/uae.html',             label: 'ذهب الإمارات'        },
          { href: '../tracker.html#mode=compare',        label: 'مقارنة دول الخليج'   },
          { href: '../countries/index.html',            label: 'صفحات الدول'         },
          { href: '../tracker.html#mode=archive',        label: 'البيانات التاريخية'   },
        ],
      },
      {
        key: 'tools',
        label: 'أدوات',
        description: 'حاسبة، تنبيهات، تصدير وسجل الأسعار',
        items: [
          { href: '../calculator.html',                label: 'حاسبة'             },
          { href: '../tools/weight-converter.html',    label: 'محول الأوزان'      },
          { href: '../tools/zakat-calculator.html',    label: 'حاسبة الزكاة'      },
          { href: '../tools/investment-return.html',   label: 'عائد الاستثمار'     },
          { href: '../tracker.html#mode=live&panel=alerts',         label: 'تنبيهات'           },
          { href: '../tracker.html#mode=exports',        label: 'تنزيلات'           },
          { href: '../gold-price-history/',              label: 'سجل الأسعار'       },
          { href: '../order-gold/',                      label: 'اطلب الذهب'        },
          { href: '../search/',                          label: 'بحث'              },
          { href: '../social/x-post-generator.html',    label: 'منشئ منشورات X'    },
        ],
      },
      {
        key: 'cities',
        label: 'المدن',
        description: 'أسعار الذهب بحسب المدينة',
        items: [
          { href: '../countries/uae/cities/dubai.html',           label: 'دبي، الإمارات'           },
          { href: '../countries/uae/cities/abu-dhabi.html',       label: 'أبوظبي، الإمارات'        },
          { href: '../countries/saudi-arabia/cities/riyadh.html', label: 'الرياض، السعودية'        },
          { href: '../countries/egypt/cities/cairo.html',         label: 'القاهرة، مصر'            },
          { href: '../countries/qatar/cities/doha.html',          label: 'الدوحة، قطر'             },
        ],
      },
      {
        key: 'goldmarkets',
        label: 'أسواق الذهب الشهيرة',
        description: 'أسواق الذهب الشهيرة والبازارات',
        items: [
          { href: '../countries/uae/markets/dubai-gold-souk.html',         label: 'سوق الذهب بدبي'        },
          { href: '../countries/egypt/markets/khan-el-khalili-cairo.html', label: 'خان الخليلي، القاهرة' },
        ],
      },
      {
        key: 'learn',
        label: 'تعلّم',
        description: 'أدلة، منهجية وأسئلة شائعة',
        items: [
          { href: '../guides/buying-guide.html',          label: 'كيفية شراء الذهب'    },
          { href: '../guides/24k-vs-22k.html',            label: '24 قيراط مقابل 22'   },
          { href: '../guides/gold-karat-comparison.html',  label: 'مقارنة العيارات'     },
          { href: '../guides/aed-peg-explained.html',      label: 'ربط الدرهم'          },
          { href: '../guides/gcc-market-hours.html',       label: 'ساعات أسواق الخليج'  },
          { href: '../guides/invest-in-gold-gcc.html',     label: 'الاستثمار في الذهب'  },
          { href: '../guides/zakat-gold-guide.html',       label: 'زكاة الذهب'          },
          { href: '../learn.html',                         label: 'دليل الذهب'          },
          { href: '../methodology.html',                   label: 'المنهجية'            },
          { href: '../learn.html#faq',                     label: 'الأسئلة الشائعة'     },
        ],
      },
      {
        key: 'insights',
        label: 'تحليلات',
        description: 'تحليل السوق والنشرات الأسبوعية',
        items: [
          { href: '../insights.html',                label: 'تحليلات الذهب'          },
          { href: '../insights.html#why-gold-moved', label: 'لماذا تحرك الذهب اليوم' },
          { href: '../insights.html#weekly-brief',   label: 'النشرة الأسبوعية'       },
        ],
      },
    ],
    langToggle: 'English',
    openMenu:   'فتح القائمة',
    closeMenu:  'إغلاق القائمة',
    mainNav:    'التنقل الرئيسي',
  },
};
