// components/nav-data.js — bilingual nav menu content data
// Edit this file to add/remove nav items, dropdowns, and labels.
//
// Phase 1 structure: Home · Prices · Tools · Shops · Learn · More (+ right actions).
// Shops stays a solo link for styling parity; Invest moves under "More".

export const NAV_DATA = {
  en: {
    home: { href: '/index.html', label: 'Home' },
    shops: { href: '/shops.html', label: 'Shops' },
    // Kept for backward compatibility with injectNav/drawer templates that reference `invest`.
    // The real Invest entry now lives inside the "More" group.
    invest: { href: '/invest.html', label: 'Invest' },
    groups: [
      {
        key: 'prices',
        label: 'Prices',
        description: 'Live tracker, country pages, cities, markets & history',
        items: [
          { href: '/tracker.html', label: 'Live Tracker' },
          { href: '/countries/uae/', label: 'UAE Gold Today' },
          { href: '/tracker.html#mode=compare', label: 'GCC Compare' },
          { href: '/content/compare-countries/', label: 'Compare Countries' },
          { href: '/content/todays-best-rates/', label: "Today's Best Rates" },
          { href: '/content/premium-watch/', label: 'Premium Watch' },
          { href: '/countries/index.html', label: 'All Countries' },
          { href: '/countries/uae/cities/dubai.html', label: 'Dubai, UAE' },
          { href: '/countries/uae/cities/abu-dhabi.html', label: 'Abu Dhabi, UAE' },
          { href: '/countries/saudi-arabia/cities/riyadh.html', label: 'Riyadh, Saudi Arabia' },
          { href: '/countries/egypt/cities/cairo.html', label: 'Cairo, Egypt' },
          { href: '/countries/qatar/cities/doha.html', label: 'Doha, Qatar' },
          { href: '/countries/uae/markets/dubai-gold-souk.html', label: 'Dubai Gold Souk' },
          {
            href: '/countries/egypt/markets/khan-el-khalili-cairo.html',
            label: 'Khan el-Khalili, Cairo',
          },
          { href: '/tracker.html#mode=archive', label: 'Price History' },
          { href: '/content/gold-price-history/', label: 'Historical Data' },
        ],
      },
      {
        key: 'tools',
        label: 'Tools',
        description: 'Calculator, alerts, exports, order & search',
        items: [
          { href: '/calculator.html', label: 'Calculator' },
          { href: '/content/tools/weight-converter.html', label: 'Weight Converter' },
          { href: '/content/tools/zakat-calculator.html', label: 'Zakat Calculator' },
          { href: '/content/tools/investment-return.html', label: 'Investment Return' },
          { href: '/tracker.html#mode=live&panel=alerts', label: 'Alerts' },
          { href: '/tracker.html#mode=exports', label: 'Downloads' },
          { href: '/content/order-gold/', label: 'Order Gold' },
          { href: '/content/search/', label: 'Search' },
          { href: '/content/embed/gold-ticker.html', label: 'Embed Widgets' },
          { href: '/content/social/x-post-generator.html', label: 'X Post Generator' },
        ],
      },
      {
        key: 'learn',
        label: 'Learn',
        description: 'Guides, methodology, glossary & FAQ',
        items: [
          { href: '/content/guides/buying-guide.html', label: 'How to Buy Gold' },
          { href: '/content/guides/24k-vs-22k.html', label: '24K vs 22K Gold' },
          { href: '/content/guides/gold-karat-comparison.html', label: 'Karat Comparison' },
          { href: '/content/guides/aed-peg-explained.html', label: 'AED Peg Explained' },
          { href: '/content/guides/gcc-market-hours.html', label: 'GCC Market Hours' },
          { href: '/content/guides/invest-in-gold-gcc.html', label: 'Invest in Gold (GCC)' },
          { href: '/content/guides/zakat-gold-guide.html', label: 'Zakat on Gold' },
          { href: '/content/guides/', label: 'All Guides' },
          { href: '/learn.html', label: 'Gold Guide' },
          { href: '/methodology.html', label: 'Methodology' },
          { href: '/content/faq/', label: 'FAQ' },
        ],
      },
      {
        key: 'more',
        label: 'More',
        description: 'Insights, news, invest & site info',
        items: [
          { href: '/insights.html', label: 'Gold Insights' },
          { href: '/insights.html#why-gold-moved', label: 'Why Gold Moved Today' },
          { href: '/insights.html#weekly-brief', label: 'Weekly Brief' },
          { href: '/content/news/', label: 'Gold News' },
          { href: '/invest.html', label: 'Invest' },
          { href: '/content/submit-shop/', label: 'Submit a Shop' },
          { href: '/content/changelog/', label: 'Changelog' },
          { href: '/privacy.html', label: 'Privacy' },
          { href: '/terms.html', label: 'Terms' },
        ],
      },
    ],
    langToggle: 'العربية',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    mainNav: 'Main navigation',
  },

  ar: {
    home: { href: '/index.html', label: 'الرئيسية' },
    shops: { href: '/shops.html', label: 'المحلات' },
    invest: { href: '/invest.html', label: 'الاستثمار' },

    groups: [
      {
        key: 'prices',
        label: 'الأسعار',
        description: 'تتبع مباشر، صفحات الدول، المدن، الأسواق والتاريخ',
        items: [
          { href: '/tracker.html', label: 'تتبع مباشر' },
          { href: '/countries/uae/', label: 'ذهب الإمارات' },
          { href: '/tracker.html#mode=compare', label: 'مقارنة دول الخليج' },
          { href: '/content/compare-countries/', label: 'مقارنة الدول' },
          { href: '/content/todays-best-rates/', label: 'أفضل الأسعار اليوم' },
          { href: '/content/premium-watch/', label: 'مراقبة العلاوة' },
          { href: '/countries/index.html', label: 'كل الدول' },
          { href: '/countries/uae/cities/dubai.html', label: 'دبي، الإمارات' },
          { href: '/countries/uae/cities/abu-dhabi.html', label: 'أبوظبي، الإمارات' },
          { href: '/countries/saudi-arabia/cities/riyadh.html', label: 'الرياض، السعودية' },
          { href: '/countries/egypt/cities/cairo.html', label: 'القاهرة، مصر' },
          { href: '/countries/qatar/cities/doha.html', label: 'الدوحة، قطر' },
          { href: '/countries/uae/markets/dubai-gold-souk.html', label: 'سوق الذهب بدبي' },
          {
            href: '/countries/egypt/markets/khan-el-khalili-cairo.html',
            label: 'خان الخليلي، القاهرة',
          },
          { href: '/tracker.html#mode=archive', label: 'سجل الأسعار' },
          { href: '/content/gold-price-history/', label: 'البيانات التاريخية' },
        ],
      },
      {
        key: 'tools',
        label: 'أدوات',
        description: 'حاسبة، تنبيهات، تصدير، طلب وبحث',
        items: [
          { href: '/calculator.html', label: 'حاسبة' },
          { href: '/content/tools/weight-converter.html', label: 'محول الأوزان' },
          { href: '/content/tools/zakat-calculator.html', label: 'حاسبة الزكاة' },
          { href: '/content/tools/investment-return.html', label: 'عائد الاستثمار' },
          { href: '/tracker.html#mode=live&panel=alerts', label: 'تنبيهات' },
          { href: '/tracker.html#mode=exports', label: 'تنزيلات' },
          { href: '/content/order-gold/', label: 'اطلب الذهب' },
          { href: '/content/search/', label: 'بحث' },
          { href: '/content/embed/gold-ticker.html', label: 'أدوات التضمين' },
          { href: '/content/social/x-post-generator.html', label: 'منشئ منشورات X' },
        ],
      },
      {
        key: 'learn',
        label: 'تعلّم',
        description: 'أدلة، منهجية، مصطلحات وأسئلة شائعة',
        items: [
          { href: '/content/guides/buying-guide.html', label: 'كيفية شراء الذهب' },
          { href: '/content/guides/24k-vs-22k.html', label: '24 قيراط مقابل 22' },
          { href: '/content/guides/gold-karat-comparison.html', label: 'مقارنة العيارات' },
          { href: '/content/guides/aed-peg-explained.html', label: 'ربط الدرهم' },
          { href: '/content/guides/gcc-market-hours.html', label: 'ساعات أسواق الخليج' },
          { href: '/content/guides/invest-in-gold-gcc.html', label: 'الاستثمار في الذهب' },
          { href: '/content/guides/zakat-gold-guide.html', label: 'زكاة الذهب' },
          { href: '/content/guides/', label: 'كل الأدلة' },
          { href: '/learn.html', label: 'دليل الذهب' },
          { href: '/methodology.html', label: 'المنهجية' },
          { href: '/content/faq/', label: 'الأسئلة الشائعة' },
        ],
      },
      {
        key: 'more',
        label: 'المزيد',
        description: 'تحليلات، أخبار، استثمار ومعلومات الموقع',
        items: [
          { href: '/insights.html', label: 'تحليلات الذهب' },
          { href: '/insights.html#why-gold-moved', label: 'لماذا تحرك الذهب اليوم' },
          { href: '/insights.html#weekly-brief', label: 'النشرة الأسبوعية' },
          { href: '/content/news/', label: 'أخبار الذهب' },
          { href: '/invest.html', label: 'الاستثمار' },
          { href: '/content/submit-shop/', label: 'أضف محلاً' },
          { href: '/content/changelog/', label: 'سجل التغييرات' },
          { href: '/privacy.html', label: 'الخصوصية' },
          { href: '/terms.html', label: 'الشروط' },
        ],
      },
    ],
    langToggle: 'English',
    openMenu: 'فتح القائمة',
    closeMenu: 'إغلاق القائمة',
    mainNav: 'التنقل الرئيسي',
  },
};
